### ISSUE TITLE
Bug / typo in candidate passed?

### ISSUE THREAD

**Issue by jasontrigg0** [hxim/Stockfish-Evaluation-Guide#1]
Hey, love this project!
In candidate passed
"  var count2 = (board(pos, square.x - 1, square.y - 2) == "p" ? 1 : 0)
             + (board(pos, square.x + 1, square.y - 2) == "p" ? 1 : 0)
             - (board(pos, square.x + 1, square.y) == "P" ? 1 : 0)
             - (board(pos, square.x + 1, square.y) == "P" ? 1 : 0);"
The second to last line should read "-board(pos, square.**x - 1**, square.y) == "P" ? 1 : 0);", right?

**Comment by hxim** [comment]
Yes, thanks for reporting this i will fix it in next version

**Comment by hxim** [comment]
should be fixed now in https://github.com/hxim/Stockfish-Evaluation-Guide/commit/9a6a90143443ef8f3204840aa03912f9dbda433c
