### ISSUE TITLE
Threats showing as non-zero

### ISSUE THREAD

**Issue by jasontrigg0** [hxim/Stockfish-Evaluation-Guide#2]
I don't completely understand what's going on, but in this position, the graph shows a number of the threats as mg=5, eg=25, although they should actually be zero. 
3r2k1/pp4p1/2p1pnNp/8/2Pr2P1/7P/PP3P2/R4RK1 w - - 1 25

**Comment by hxim** [comment]
Thank. It is a bug i forgot to check "For graph" checkbox for "Weak unopposed pawn" and it is not showing in graph and because of it numbers are not correct.

**Comment by hxim** [comment]
Should be fixed now
