### ISSUE TITLE
Bug in Rank Threat?

### ISSUE THREAD

**Issue by jasontrigg0** [hxim/Stockfish-Evaluation-Guide#5]
The description says "Threat bonus depending on rank only applied if multiple threats from minors or rooks are present."

But in the code 

```function rank_threat(pos, square) {
  if (square == null) return sum(pos, rank_threat);
  return ((minor_threat(pos, square) > 1)
        + (rook_threat(pos, square) > 1)
  ) * square.y;
}
```

minor_threat(pos, square) and rook_threat(pos, square) return a value based on the *type* of threat, not the number of threats, so rank_threat will be non-zero for a single minor or rook threat. 

For example: 
r2q1rk1/2p2ppp/p1n1pn2/1b4B1/1bpP4/2N1PN2/1PQ1BPPP/R4RK1 w - - 0 12

**Comment by hxim** [comment]
I verified code is equivalent to what is in stockfish.
The description is wrong and i will fix it in next version.
Condition on > 1 is ensuring we exclude pawns which is type 1.
In stockfish we have this:

```
if (type_of(pos.piece_on(s)) != PAWN)
score += ThreatByRank * (int)relative_rank(Them, s);

```
