### ISSUE TITLE
pass FEN with url

### ISSUE THREAD

**Issue by vondele** [hxim/Stockfish-Evaluation-Guide#6]
chessdb and lichess allow to pass the FEN position as part of the URL.  Would be great to have this for the evaluation guide as well. Maybe this is already possible, but I couldn't find the syntax yet.

https://www.chessdb.cn/queryc_en/?rnbq1rk1/ppp3bp/3p2p1/3Ppp1n/2P1P3/2N1BP2/PP1QN1PP/R3KB1R%20b%20KQ%20-%203%209

https://lichess.org/analysis/standard/rnbq1rk1/ppp3bp/3p2p1/3Ppp1n/2P1P3/2N1BP2/PP1QN1PP/R3KB1R%20b%20KQ%20-%203%209

**Comment by hxim** [comment]
You can use URL like this:
https://hxim.github.io/Stockfish-Evaluation-Guide/index.html?p=rnbq1rk1/ppp3bp/3p2p1/3Ppp1n/2P1P3/2N1BP2/PP1QN1PP/R3KB1R%20b%20KQ%20-%203%209
I wrote about it here:
https://groups.google.com/forum/#!msg/fishcooking/kHs9Ajva_lQ/1b2oEvI9BAAJ
You can put both FEN or PGN and also name of page for eval term like "King Danger" there.

**Comment by vondele** [comment]
BTW, tcec now links to this (right click the board, to get the actual fen).... I hope this makes more people find the tool!

**Comment by hxim** [comment]
> BTW, tcec now links to this (right click the board, to get the actual fen).... I hope this makes more people find the tool!

Great :-)
