### ISSUE TITLE
License details

### ISSUE THREAD

**Issue by daviddallet** [hxim/Stockfish-Evaluation-Guide#9]
Hi,

I've had a look at [Stockfish Evaluation Guide github pages](https://hxim.github.io/Stockfish-Evaluation-Guide/).

Your project is great and is a real shortcut for Stockfish evaluation understanding. Would it be possible to add explicitly the proper license information? I know Stockfish is already open-source copyleft but using your project could be a real shortcut for new implementations based on Stockfish knowledge.

As a side note there is a [current competition on kaggle](https://www.kaggle.com/competitions/fide-google-efficiency-chess-ai-challenge/) and I'm pretty sure many people are interested in you project ;) 

Regards,

David

**Comment by hxim** [comment]
Hi I added license info (GNU General Public License version 3 - same as official stockfish) as you requested.

**Comment by daviddallet** [comment]
Great, thank you for your work.
